from __future__ import annotations

from pathlib import Path
import unittest


WEB_DIR = Path(__file__).resolve().parents[1] / "app" / "web"


class WebStaticUiContractTests(unittest.TestCase):
    def test_index_contains_status_filters_ranking_and_trend_controls(self) -> None:
        html = (WEB_DIR / "index.html").read_text(encoding="utf-8")

        self.assertIn('data-page="ranks"', html)
        self.assertIn('href="./insights.html"', html)
        self.assertIn('id="dataSource"', html)
        self.assertIn('id="recentDateButtons"', html)
        self.assertIn('id="compareYesterday"', html)
        self.assertIn('id="clearCompare"', html)
        self.assertIn('id="snapshot_date"', html)
        self.assertIn('id="site"', html)
        self.assertIn('id="board_type"', html)
        self.assertIn('id="category_key"', html)
        self.assertIn('id="has_price"', html)
        self.assertIn('id="top_n"', html)
        self.assertIn('id="sort_by"', html)
        self.assertIn('id="sort_order"', html)
        self.assertIn('id="keyword"', html)
        self.assertIn('id="searchRanks"', html)
        self.assertIn('id="downloadCsv"', html)
        self.assertIn("较昨日", html)
        self.assertIn("当日销量(估)", html)
        self.assertIn("近30天销量(估)", html)
        self.assertIn("近1年销量(估)", html)
        self.assertIn("销量趋势", html)
        self.assertIn('id="ranksTable"', html)
        self.assertIn('id="trendModal"', html)
        self.assertIn('id="trendClose"', html)
        self.assertIn('id="trendTitle"', html)
        self.assertIn('id="trendChart"', html)
        self.assertIn('id="trendTable"', html)

    def test_insights_contains_filters_and_insight_panels(self) -> None:
        html = (WEB_DIR / "insights.html").read_text(encoding="utf-8")

        self.assertIn('data-page="insights"', html)
        self.assertIn('href="./index.html"', html)
        self.assertIn('href="./product.html"', html)
        self.assertIn('id="dataSource"', html)
        self.assertIn('id="snapshot_date"', html)
        self.assertIn('id="site"', html)
        self.assertIn('id="board_type"', html)
        self.assertIn('id="category_key"', html)
        self.assertIn('id="has_price"', html)
        self.assertIn('id="top_n"', html)
        self.assertIn('id="sort_by"', html)
        self.assertIn('id="sort_order"', html)
        self.assertIn('id="keyword"', html)
        self.assertIn('id="searchRanks"', html)
        self.assertIn('id="runInsights"', html)
        self.assertIn('id="analysisScope"', html)
        self.assertIn('id="analysisAsin"', html)
        self.assertIn('id="reviewInsights"', html)
        self.assertIn('id="reviewRatingChart"', html)
        self.assertIn('id="reviewSentimentChart"', html)
        self.assertIn('id="reviewSnippetList"', html)
        self.assertIn('id="reviewTopicDetail"', html)
        self.assertIn('id="trafficKeywords"', html)
        self.assertIn('id="conversionKeywords"', html)
        self.assertIn('id="monthlySalesInsights"', html)
        self.assertIn('id="monthlySalesCompetitor"', html)
        self.assertIn('id="downloadMonthlySalesCsv"', html)
        self.assertIn('id="styleTrendInsights"', html)
        self.assertIn('id="styleTrendMonthlyTable"', html)
        self.assertIn('id="downloadStyleTrendCsv"', html)
        self.assertNotIn('id="ranksTable"', html)
        self.assertNotIn('id="trendModal"', html)

    def test_product_contains_single_item_focus_and_insight_panels(self) -> None:
        html = (WEB_DIR / "product.html").read_text(encoding="utf-8")

        self.assertIn('data-page="product"', html)
        self.assertIn('href="./index.html"', html)
        self.assertIn('href="./insights.html"', html)
        self.assertIn('id="snapshot_date"', html)
        self.assertIn('id="site"', html)
        self.assertIn('id="board_type"', html)
        self.assertIn('id="analysisScope"', html)
        self.assertIn('id="analysisAsin"', html)
        self.assertIn('id="productFocus"', html)
        self.assertIn('id="backToCategoryList"', html)
        self.assertIn('id="runInsights"', html)
        self.assertIn('id="reviewInsights"', html)
        self.assertIn('id="reviewRatingChart"', html)
        self.assertIn('id="reviewSentimentChart"', html)
        self.assertIn('id="reviewSnippetList"', html)
        self.assertIn('id="reviewTopicDetail"', html)
        self.assertIn('id="trafficKeywords"', html)
        self.assertIn('id="conversionKeywords"', html)
        self.assertIn('id="monthlySalesKpiCards"', html)
        self.assertIn('id="monthlySalesTrendChart"', html)
        self.assertIn('id="monthlySalesInsights"', html)
        self.assertIn('id="monthlySalesCompetitor"', html)
        self.assertIn('id="styleTrendInsights"', html)
        self.assertIn('id="styleTrendMonthlyTable"', html)
        self.assertNotIn('id="ranksTable"', html)
        self.assertNotIn('id="trendModal"', html)

    def test_app_contains_compare_and_trend_logic_entrypoints(self) -> None:
        js = (WEB_DIR / "app.js").read_text(encoding="utf-8")

        self.assertIn("const APP_PAGE", js)
        self.assertIn("const IS_PRODUCT_PAGE", js)
        self.assertIn("function compareWithPreviousDay", js)
        self.assertIn("function showSalesTrendForItem", js)
        self.assertIn("function collectSalesTrendWithinOneYear", js)
        self.assertIn("function closeTrendModal", js)
        self.assertIn("function runCompetitiveInsights", js)
        self.assertIn("function collectScopeHistoryWithinOneYear", js)
        self.assertIn("function getOfficialInsights", js)
        self.assertIn("function normalizeSelectedAsin", js)
        self.assertIn("function buildReviewDetailFromOfficial", js)
        self.assertIn("function renderReviewDeepDive", js)
        self.assertIn("function buildKeywordInsightRows", js)
        self.assertIn("function buildKeywordInsightRowsFromOfficial", js)
        self.assertIn("function buildCompetitorMonthlySalesRows", js)
        self.assertIn("function renderMonthlySalesCompetitorTable", js)
        self.assertIn("function downloadMonthlySalesCsv", js)
        self.assertIn("function buildStyleTrendLines", js)
        self.assertIn("function buildStyleTrendRows", js)
        self.assertIn("function renderStyleTrendMonthlyTable", js)
        self.assertIn("function downloadStyleTrendCsv", js)
        self.assertIn("function buildStyleTrendLinesFromOfficial", js)
        self.assertIn("function populateAnalysisAsinOptions", js)
        self.assertIn("function applyInitialUrlFilters", js)
        self.assertIn("function buildProductPageHref", js)
        self.assertIn("function buildCategoryListHref", js)
        self.assertIn("function updateProductFocus", js)
        self.assertIn("function renderReviewTopicDetail", js)
        self.assertIn("function renderMonthlySalesKpiCards", js)
        self.assertIn("function renderMonthlySalesTrendChart", js)
        self.assertIn("function updateProductBackLink", js)
        self.assertIn("recentDateButtons", js)
        self.assertIn("dataSource", js)
        self.assertIn("sales_month", js)
        self.assertIn("trendModal", js)
        self.assertIn("INSIGHTS_PATH_PREFIX", js)


if __name__ == "__main__":
    unittest.main()
